### ISSUE TITLE
第一次输入范围错误会出现异常

### ISSUE THREAD

**Issue by LuckyZone** [InsulatingShell/ACTurnipPriceModel-cn#1]
白萝卜价格趋势模型(简体中文)
Github: InsulatingShell
https://github.com/InsulatingShell/ACTurnipPriceModel-cn/
微博：@绝缘壳
版本：v 1.0
最后更新时间： Mar 23
目前如果输入了不含数字的内容，会直接退出，重新运行即可

请输入周日买入价，回车结束输入
30
一般来说，白萝卜的购入价在 90-110 之间，如果确定没有输错，请再输入一次
100
周日买入价为： None

请输入周一收购价，回车结束输入
101
周一买入价为： 101
Traceback (most recent call last):
  File ".\Mar23.py", line 269, in <module>
    main()
  File ".\Mar23.py", line 259, in main
    turnip.Mon()
  File ".\Mar23.py", line 189, in Mon
    Turnip.roughModel(self)
  File ".\Mar23.py", line 121, in roughModel
    X = (float(Turnip.mon)/float(Turnip.sun))*100
TypeError: float() argument must be a string or a number, not 'NoneType'

**Comment by InsulatingShell** [comment]
非常感谢你的反馈！我今天稍后会解决这个问题。

**Comment by InsulatingShell** [comment]
版本v.1.0.1已解决了这个问题，感谢你的反馈！
